name: notes_app
description: A Notes app using bloc and hive.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
